name: local_ledger
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flyout: ^1.0.0
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  snackbar: ^1.0.2
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.12
  synchronized: ^3.0.1
  fast_log: ^1.0.2
  equatable: ^2.0.5
  json_compress: ^1.0.2
  intl: any
  dialoger: ^1.0.0
  currency_text_input_formatter: ^2.1.8
  padded: ^1.0.1
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
